name: bangerlabz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.0
  iconify_flutter: ^0.0.1
  velocity_x: ^4.3.0
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_keyboard_visibility: ^6.0.0
  flutter_form_builder: ^9.1.0
  form_validator: ^2.1.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/default_profile.webp
  - assets/images/map_sample.webp
  - assets/images/paypal.png
  - assets/images/zelle.png
  - assets/images/cashapp.png
  - assets/images/applepay.png
  - assets/images/Lightmode_logo.png
  - assets/images/gmail.png