name: ecommerceapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AfacadFlux
      fonts:
        - asset: fonts/AfacadFlux-Black.ttf
  assets:
  - assets/images/default_profile.webp
  - assets/images/map_sample.webp