// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIxpvSmiIX2kbJQHTS1wwbSNpQKYcZEA',
    appId: '1:39620182153:web:ba49b44b524842e17cc658',
    messagingSenderId: '39620182153',
    projectId: 'banger-labz',
    authDomain: 'banger-labz.firebaseapp.com',
    storageBucket: 'banger-labz.firebasestorage.app',
    measurementId: 'G-T1BMF6RQFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVtJ7wqDuoyZ9w1wH5aRbfifRxL5JQAw',
    appId: '1:39620182153:android:0a51dab5e3fe3fed7cc658',
    messagingSenderId: '39620182153',
    projectId: 'banger-labz',
    storageBucket: 'banger-labz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1o6en4xb0b3QcTQJxiKKn-t8ITApKGc',
    appId: '1:39620182153:ios:6402ae991809285f7cc658',
    messagingSenderId: '39620182153',
    projectId: 'banger-labz',
    storageBucket: 'banger-labz.firebasestorage.app',
    iosBundleId: 'com.example.bangerlabz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1o6en4xb0b3QcTQJxiKKn-t8ITApKGc',
    appId: '1:39620182153:ios:6402ae991809285f7cc658',
    messagingSenderId: '39620182153',
    projectId: 'banger-labz',
    storageBucket: 'banger-labz.firebasestorage.app',
    iosBundleId: 'com.example.bangerlabz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIxpvSmiIX2kbJQHTS1wwbSNpQKYcZEA',
    appId: '1:39620182153:web:445a5cdcca389c217cc658',
    messagingSenderId: '39620182153',
    projectId: 'banger-labz',
    authDomain: 'banger-labz.firebaseapp.com',
    storageBucket: 'banger-labz.firebasestorage.app',
    measurementId: 'G-9LRDS645KC',
  );
}
